name: Deploy PR Preview

on:
  pull_request:
    types: [opened, reopened, synchronize]

env:
  VITE_STATSIG_CLIENT_KEY: client-FccOCTznRdYyGr7cx3vJoyoWyO1BTqBzv6S2g1lYPvB

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      # Checkout the latest code using v4 to match the other actions
      - uses: actions/checkout@v4

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the project
      - name: Build
        run: npm run build

      # Deploy preview using updated action
      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v2  # Ensure using the latest stable version
        with:
          source-dir: ./dist/
          preview-branch: gh-pages
          umbrella-dir: pr-preview
